In [1]:
import numpy as np

In [2]:
np.array([1,2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([1,2, 3, 4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr = np.array([1,2, "3", 4])
arr

array(['1', '2', '3', '4'], dtype='<U21')

In [6]:
type(arr)

numpy.ndarray

In [7]:
#attributes
arr.ndim

1

In [8]:
arr.size

4

In [9]:
arr.dtype

dtype('<U21')

In [10]:
arr.itemsize #memory bytes

84

In [11]:
arr.itemsize*6 # + bufffer memory

504

In [12]:
sys.getsizeof(arr)

NameError: name 'sys' is not defined

In [13]:
import sys as sys
sys.getsizeof(arr)

448

In [14]:
arr

array(['1', '2', '3', '4'], dtype='<U21')

In [15]:
arr.shape

(4,)

In [16]:
#2d array
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [17]:
np.array([[1,2], [3,4, 5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [18]:
arr2 =np.array([[1,2], [3,4]])

In [20]:
arr2.shape

(2, 2)

In [21]:
arr2.dom

AttributeError: 'numpy.ndarray' object has no attribute 'dom'

In [22]:
arr2.dim

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [23]:
arr3 = np.array([[[1,2, 3], [1, 2, 3]]])
arr3

array([[[1, 2, 3],
        [1, 2, 3]]])

In [24]:
arr3.shape

(1, 2, 3)

In [25]:
# array creation routines

In [26]:
arr4 =np.arange(10, 20 , 2)

array([10, 12, 14, 16, 18])

In [27]:
arr4.reshape(10, 2)

NameError: name 'arr4' is not defined

In [28]:
arr4 =np.arange(10, 20)

In [29]:
arr4.reshape(5, 2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [30]:
np.linspace(1, 7, 3)

array([1., 4., 7.])

In [31]:
np.linspace(1, 2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [32]:
np.full(10, -1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [33]:
np.full((10, 2), -10)

array([[-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10]])

In [34]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.eye(2, 2)

array([[1., 0.],
       [0., 1.]])

In [37]:
#slice/index 2d array

In [38]:
arr = np.arange(25).reshape(5, 5)

In [39]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr[1, 0]

5

In [41]:
arr[1]

array([5, 6, 7, 8, 9])

In [42]:
arr[1][0]

5

In [43]:
arr[1, 0]

5

In [44]:
arr[-4, -5]

5

In [45]:
#slicing
#var_name[start:stop:step, start:stop:step]

In [46]:
arr[1:,]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr[1:3,]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
arr[1:3, 1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [49]:
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [50]:
arr = np.arange(25).reshape(5, 5)
#slice first two rows, last two columns
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr[0:2, 3:]

array([[3, 4],
       [8, 9]])

In [52]:
#math operations
# multiply - by element, dot product --> h/w

In [53]:
#aggregation

In [54]:
arr.max()

24

In [55]:
arr.std() #standard deviation

7.211102550927978

In [56]:
arr.var() #variance

52.0

In [57]:
#joining/splitting

In [58]:
a = np.arange(25).reshape(5, 5)
b = np.arange(25, 50).reshape(5, 5)

In [59]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [62]:
np.concatenate((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [63]:
np.concatenate((a,b), axis=1)

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

In [64]:
#stacking -> hstack(), vstack()

In [65]:
np.hstack((a, b))

array([[ 0,  1,  2,  3,  4, 25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9, 30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14, 35, 36, 37, 38, 39],
       [15, 16, 17, 18, 19, 40, 41, 42, 43, 44],
       [20, 21, 22, 23, 24, 45, 46, 47, 48, 49]])

In [66]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [67]:
np.stack((a, b))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [68]:
np.stack((a, b)).shape

(2, 5, 5)

In [70]:
arr = np.column_stack((a, b))

(5, 10)

In [71]:
np.split(arr, 5)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [72]:
np.hsplit(arr, 5)

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20]]),
 array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [73]:
np.vsplit(arr, 5)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [74]:
arr2

array([[1, 2],
       [3, 4]])

In [75]:
arr2.flatten()

array([1, 2, 3, 4])

In [76]:
arr2.ravel()

array([1, 2, 3, 4])

In [77]:
arr2.reshape(1, -1)

array([[1, 2, 3, 4]])

In [78]:
arr2.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [79]:
arr2.transpose()

array([[1, 3],
       [2, 4]])

In [80]:
arr2.T

array([[1, 3],
       [2, 4]])

In [81]:
# u1 -> [1, -1, 4, ]

In [82]:
movie_ids = np.arange(1300, 2300)

In [86]:
movie_ids

NameError: name 'movie_ids' is not defined

In [87]:
movie_ids = np.arange(1300, 2300)

In [88]:
movie_ids

array([1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310,
       1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321,
       1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332,
       1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343,
       1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354,
       1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365,
       1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376,
       1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387,
       1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398,
       1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409,
       1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420,
       1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431,
       1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442,
       1443, 1444, 1445, 1446, 1447, 1448, 1449, 14

In [89]:
movie_ids = np.arange(1301, 2301)
movie_ids

array([1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311,
       1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322,
       1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333,
       1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344,
       1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355,
       1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366,
       1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377,
       1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388,
       1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399,
       1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410,
       1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421,
       1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432,
       1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443,
       1444, 1445, 1446, 1447, 1448, 1449, 1450, 14

In [90]:
import random as r

In [91]:
user_ratings = np.full(1000, -1)

In [92]:
user_ratings

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [93]:
for i in range(1301, 2301):
    rat = r.randint(0, 10)
    user_ratings[i] = rat

IndexError: index 1301 is out of bounds for axis 0 with size 1000

In [94]:
for i in range(0, 1000):
    rat = r.randint(-1, 10)
    user_ratings[i] = rat

In [95]:
user_ratings

array([ 1,  7,  1,  2,  1,  2,  5,  4,  6,  0,  3,  4, 10,  9,  7,  3,  9,
        8,  9,  1,  3,  9,  0,  2,  3,  9,  5,  4,  4,  3,  8, 10,  9,  9,
        7,  2,  6,  1,  0,  4,  3,  4,  9,  8,  0,  0,  4,  9,  4,  6,  2,
        2, 10,  3,  7,  7,  2,  9,  4,  4,  2,  3,  2,  8,  3,  9,  2,  0,
        5,  9,  2, 10,  4,  8,  0,  2,  7,  0,  0,  9,  2,  2,  4,  8,  5,
        2,  7,  2,  1,  2, 10,  3, 10,  4,  8,  5,  8,  7, 10,  6,  7,  1,
        1,  0,  5, 10,  0,  6,  1,  5,  1,  4,  1,  9,  1,  5,  9,  5,  7,
       10,  6,  0,  3,  7,  3,  9, 10,  4,  3,  1,  5,  9,  5,  6,  5,  2,
       10,  0,  2,  8,  8,  8,  0,  4,  5,  1,  7,  0, 10,  6,  1,  4,  1,
        4,  3,  4,  3,  0,  4,  4,  2,  3,  6,  1,  4,  0,  2,  7,  7,  1,
        4, 10,  5,  7,  7,  3,  2,  4,  2,  5,  4, 10,  1,  8,  7,  9,  0,
        1,  6, 10,  9,  1,  3,  6,  8,  2,  0,  5,  4,  0,  3,  1,  8,  2,
        8,  1,  7,  9,  8,  2,  7,  8,  2,  5,  3,  7,  5,  6,  2,  9,  1,
        8,  1,  4,  3,  5

In [96]:
for i in range(0, 1000):
    rat = r.randint(-1, 10)
    user_ratings[i] = rat


In [97]:
user_ratings

array([ 2,  3,  2,  3,  5,  6,  8,  0,  6, 10, -1,  8, -1,  2,  4, -1,  4,
        7,  8, 10,  9,  8,  8, -1,  7,  2,  6, -1, 10,  3,  2,  7,  1,  2,
       -1,  7,  5,  2, -1,  3,  0,  8, 10,  2, 10,  9, 10,  1,  5,  8, 10,
        0,  8,  5,  7, 10,  9,  1,  5,  1, 10,  6,  3,  9, -1, 10,  8,  1,
        4,  5,  2,  8,  3,  8,  6,  2,  6,  7,  1, -1, 10,  1,  2,  9,  6,
        3,  5,  5, 10, 10, 10,  2,  6,  6,  4,  9, 10,  6,  5, -1,  1,  4,
       10,  5,  1, 10,  7,  2,  9,  7,  4,  5,  5,  5,  0,  4,  9,  6,  6,
       10,  3,  1,  7,  4,  9,  7,  3, -1, -1,  4,  0,  1,  6,  0, 10,  1,
        2,  4,  6,  1,  1,  5,  9,  9,  7,  3,  3, -1,  8,  7,  0,  9,  6,
        9,  1,  4,  5,  1,  4,  6,  2,  3,  0,  0,  1,  2,  0,  8,  3,  0,
        0,  7,  8, 10,  9,  6, -1,  2,  8,  8,  3,  6,  0,  0,  9,  4,  2,
        9,  5,  4, 10,  0,  5,  6, 10, 10, -1,  2,  0,  4,  3,  2,  0,  2,
        4, 10,  9, 10,  5,  1,  8,  5,  1,  2,  7,  2,  1,  6,  4,  7,  6,
       10,  4,  5, 10, -1

In [98]:
movie_ratings.concatenate(user_ratings)

NameError: name 'movie_ratings' is not defined

In [100]:
final = np.concatenate((movie_ids, user_ratings))

In [101]:
final

array([1301, 1302, 1303, ...,   10,   10,    7])

In [102]:
final.reshape(1000, 2)

array([[1301, 1302],
       [1303, 1304],
       [1305, 1306],
       ...,
       [   1,    1],
       [   3,   10],
       [  10,    7]])